function [f_eq] = addAxialPointLoad(p_bar, L, a)
% outputs equivalent nodal force vector for concentrated vertical point
% load at point a from node 1 of an element of length L with intensity w
% bar

f_eq = p_bar .*... 
        [1-(a/L);...
        0;...
        0;...
        a/L;...
        0;...
        0];
end

