function [f_eq] = addAxialUDL(p_bar, L)
% outputs equivalent nodal force vector for concentrated vertical point
% load at point a from node 1 of an element of length L with intensity w
% bar

f_eq = p_bar .*... 
        [L/2;...
        0;...
        0;...
        L/2;...
        0;...
        0];
end

