function [f_eq] = addTransversePointLoad(w_bar, L, a)
% outputs equivalent nodal force vector for concentrated vertical point
% load at point a from node 1 of an element of length L with intensity w
% bar

f_eq = w_bar .* [0;...
        1 - 3 * a^2/L^2 + 2 * a^3/L^3;...
        a^3/L^2 - 2 * a^2/L + a;...
        0;...
        3 * a^2/L^2 + 2 * a^3/L^3;...
        a^3/L^2 - 2 * a^2/L];
end

