function [f_eq] = addTransverseLVL(w_bar, L)
% outputs equivalent nodal force vector for linearly varying load with
% peak value w_bar

f_eq = w_bar .*... 
        [0;...
        3 * L / 20;...
        L^2 / 30;...
        0;...
        7 * L / 20;...
        -L^2 / 20];
end

